### PR TITLE
Update stegosaurus_ui.c (fix display)

### PR DESCRIPTION
**Pull request by trebmuh**
Looks to be a mistake in the GUI display.
Fixing it here.

### CODE REVIEW

**Comment by trebmuh** [comment]
@thunderox : any issue with merging this one?

**Comment by trebmuh** [comment]
@thunderox ping

**Review by thunderox — APPROVED** [review]

**Comment by trebmuh** [comment]
@thunderox it seems you approved the changes, but didn't merged it into master. Was this intended?

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
